### ISSUE TITLE
[FIXED] Getting the exporter working with Gmod servers.

### ISSUE THREAD

**Issue by Unyxos** [Unyxos/srcds_exporter#1]
Due to a different format in the data sent by the server, the exporter isn't working with Gmod (yet).

CSGO format 
![unknown](https://user-images.githubusercontent.com/11515332/71645098-34931f00-2cd3-11ea-9843-c5ca61d2c276.png)

Gmod format
![gmod](https://user-images.githubusercontent.com/11515332/71645099-3826a600-2cd3-11ea-98bc-034743eb5d03.png)

Thanks to CTX for pointing that !

**Comment by bjerrecs** [comment]
Would be cool if this could be fixed soon 😄
Would be happy to help

-ctx

**Comment by Unyxos** [comment]
Hey Simon!
I will most likely look into it today/this week, this shouldn’t be something hard to fix, I’ll also try to test every source game to make sure it’s working with everything 👌

**Comment by Unyxos** [comment]
Fixed in https://github.com/Unyxos/srcds_exporter/pull/2

If you encounter any issue with gmod feel free to re-open this issue !
