### ISSUE TITLE
Error while fetching metrics from server

### ISSUE THREAD

**Issue by Baldurrr** [Unyxos/srcds_exporter#16]
Hi guys,

I was trying the exporter, but encounter the same error again and again as you can see below.
![cs-exp-error](https://user-images.githubusercontent.com/77190420/229904230-3e7cb344-e01c-41a5-af72-fe31ab611342.png)

I precise that i used the same config files as describe on this repository, exporter is install on the game server.

docker-compose file:
```version: '3.3'
services:
  srcds_exporter:
    ports:
      - '9591:9591'
    container_name: srcds_exporter
    restart: always
    image: corentincl/srcds_exporter
```

On the prometheus side:
```  - job_name: 'srcds'
    static_configs:
      - targets: ["192.168.1.210:27015:12345:csgo"]

    relabel_configs:
      - source_labels: [__address__]
        regex: "(.+):.+:.+:.+"
        replacement: "$1"
        target_label: __param_ip
      - source_labels: [__address__]
        regex: ".+:(.+):.+:.+"
        replacement: "$1"
        target_label: __param_port
      - source_labels: [__address__]
        regex: ".+:.+:(.+):.+"
        replacement: "$1"
        target_label: __param_password
      - source_labels: [__address__]
        regex: ".+:.+:.+:(.+)"
        replacement: "$1"
        target_label: __param_game
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.210:9591
```

And as you can see all the metrics are returning 0 :
![image](https://user-images.githubusercontent.com/77190420/229905095-6e10e48a-1d94-44bb-9f7a-25bab1518916.png)

Thanks in advance guys

**Comment by Unyxos** [comment]
Hello!

Is the server running with the -usercon argument ?

I noticed it needs to be in the server's launch parameters for the export to be able to use rcon

**Comment by Baldurrr** [comment]
Hi,

Just added the "-usercon" to the startup command and now its working. All metrics seems to be ok but the map metrics is always returnig 0, is it normal ?

Thanks a lot

**Comment by Unyxos** [comment]
Hey!

I'd have to double check as it's not super fresh in my mind rn, but I believe it's a count of mapchanges when the server was alive (and resets when the server is restart)
Have you tried changing map and checking if the metric updates?

**Comment by Baldurrr** [comment]
Hi Unyxos,

I have just tested to change the map, and the "srcds_maps" metrics changed to 1. So, i assume that is a counter as you said.
But i also see that the field "map" in all the metrics changed too (switched from dust2 to vertigo), as you can see below:

![image](https://user-images.githubusercontent.com/77190420/230940040-5267c473-f1e9-495e-a5e1-23a450411962.png)

**Comment by Unyxos** [comment]
Hey @Baldurrr !

Yeah this is a normal behavior, the "map" label will be set for all the metrics that belongs to the same "source" (in this case, your only (I suppose ?) csgo server), if you had 2 servers running, one with de_vertigo and the other one with de_dust2, one would show "de_vertigo" in all labels while the other one would show "de_dust2".

Labels can be used for better filtering (for example, you only want the CPU usage for servers running dust2, that'd be : `srcds_cpu{map="de_dust2"}`)

**Comment by Baldurrr** [comment]
Hi, 
Thanks a lot for all this information, i'm closing the issue.
