### ISSUE TITLE
Other games?

### ISSUE THREAD

**Issue by sahara101** [Unyxos/srcds_exporter#18]
Hello :)

Is it possible to add other games like sons of the forest? I have a dedicated server installed via docker.

Thanks!

**Comment by Unyxos** [comment]
Hi!

It doesn't seem Sons of the Forest was made using Source engine sadly, so it'd be hard (to not say "impossible") to add it to this project.

However, depending on what metrics the game exposes & how, it might be possible to make something similar :)

**Comment by sahara101** [comment]
Steam API is giving this json info:

{"response":{"servers":[{"addr":"xxx:27016","gameport":8766,"steamid":"serverid","name":"Name","appid":1326470,"gamedir":"sotf","version":"0.11.3.0.0","product":"Sons Of the Forest","region":-1,"players":0,"max_players":4,"bots":0,"map":"Custom","secure":false,"dedicated":true,"os":"w","gametype":"V:7gzfshiNku/2sJrOxHTn2eOuBAA=,G:e6dd4563-f878-4d1b-abf8-b7d90a1666ca,Pwd:31,"}]}}

**Comment by John-H-Smith** [comment]
> Steam API is giving this json info:
> 
> {"response":{"servers":[{"addr":"xxx:27016","gameport":8766,"steamid":"serverid","name":"Name","appid":1326470,"gamedir":"sotf","version":"0.11.3.0.0","product":"Sons Of the Forest","region":-1,"players":0,"max_players":4,"bots":0,"map":"Custom","secure":false,"dedicated":true,"os":"w","gametype":"V:7gzfshiNku/2sJrOxHTn2eOuBAA=,G:e6dd4563-f878-4d1b-abf8-b7d90a1666ca,Pwd:31,"}]}}

Yeah, it is - but it shouldn't be part of that repo. srcds_exporter is only for exporting games made with the source engine. Maybe you could spin up a steam exporter though.

**Comment by sahara101** [comment]
Thanks for the answer :) I made the data available via gamedig
