### ISSUE TITLE
State up but always offline

### ISSUE THREAD

**Issue by John-H-Smith** [Unyxos/srcds_exporter#7]
After added correctly to Prometheus, state of the target is "up".
So port and so on should be correct.
But when I try to access the metrics in Prometheus graph with srcds_status (directly copied from metrics), it is always value 0.
But of course the server is running.
Do you have an Idea?

**Comment by Unyxos** [comment]
Hello! Which game are you trying to monitor ?
I haven't worked for a while on this project so some things may have changed in srcds, even though that would be strange.

I'll try to push a new version in some time that is more clean and supports more games!

**Comment by John-H-Smith** [comment]
Thank you for your quick reply!
I am trying to monitor a gmod server.
Btw, the metrics (accessed over browser) are showing the server as online.

**Comment by Unyxos** [comment]
Hmm so that's only the Grafana dashboard returning incorrect infos ? Are you using the one provided in the repo ? If so, I know it's a wrong version I quickly uploaded but corrected after (the exporter wasn't supposed to be public at first, it was made to monitor CSGO servers during a LAN)

**Comment by John-H-Smith** [comment]
No, its not only grafana, even if I try to access it in prometheus itself.
Have a look at this screenshot in prometheus graph: [https://ibb.co/YycHK8w](https://ibb.co/YycHK8w)
But server is running and metrics accessed over browser are showing it is online.

**Comment by Unyxos** [comment]
Can you add me on Discord so we can take a closer look this evening ? :) 
my handle is Unyxos#4242

**Comment by Unyxos** [comment]
Will edit readme to add "params" part for prometheus config
